// MEDIA SIZE
const MEDIA_WIDTH_SM = '576px'
const MEDIA_WIDTH_MD = '768px'
const MEDIA_WIDTH_LG = '992px'
const MEDIA_WIDTH_XL = '1200px'

// COLOR
const COLOR_PRIMARY = '#21F662' // Light Green
const COLOR_BACKGROUND = '#F0FFF0' // Ultra Light Green
const COLOR_DANGER = '#FF5050'
const COLOR_DANGER_LIGHT = '#FFDDDD'
const COLOR_DANGER_DARK = '#DD2F2F'
const COLOR_SUCCESS = '#21F662'
const COLOR_SUCCESS_LIGHT = '#F0FFF0'
const COLOR_SUCCESS_DARK = '#17B547'
const COLOR_SECONDARY = '#999999'
const COLOR_SECONDARY_LIGHT = '#eeeeee'
const COLOR_SECONDARY_DARK = '#646464'
const COLOR_TEXT_LIGHT = '#ffffff'
const COLOR_TEXT_DARK = '#000000'

export {
  MEDIA_WIDTH_SM,
  MEDIA_WIDTH_MD,
  MEDIA_WIDTH_LG,
  MEDIA_WIDTH_XL,
  COLOR_PRIMARY,
  COLOR_BACKGROUND,
  COLOR_DANGER,
  COLOR_DANGER_LIGHT,
  COLOR_DANGER_DARK,
  COLOR_SUCCESS,
  COLOR_SUCCESS_LIGHT,
  COLOR_SUCCESS_DARK,
  COLOR_SECONDARY,
  COLOR_SECONDARY_LIGHT,
  COLOR_SECONDARY_DARK,
  COLOR_TEXT_LIGHT,
  COLOR_TEXT_DARK,
}
